{% set version = "2.00" %}

package:
    name: ndiff
    version: {{ version }}

source:
    url: ftp://ftp.math.utah.edu/pub/misc/ndiff-{{ version }}.tar.gz
    sha256: f2bbd9a2c8ada7f4161b5e76ac5ebf9a2862cab099933167fe604b88f000ec2c

requirements:
    build:
        - clang_osx-64
        - gfortran_osx-64
    run:
        - clang_osx-64
        - gfortran_osx-64

